# Generated by Django 5.0.2 on 2024-03-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='std_id',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
